# fly.toml app configuration file generated for olivander-wand-bot on 2023-06-19T15:03:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "olivander-wand-bot"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
